"""
CLI tools for Player10 simulations and utilities.

Convenience module so you can run:
  python -m players.player_10.tools.flexible_runner ...
  python -m players.player_10.tools.run_simulations ...
  python -m players.player_10.tools.debug_toggle ...
"""
